site_name: Feima Robotics Develop Document
site_url: https://feima-robotics.github.io/
repo_url: https://github.com/Feima-Robotics/Feima-Robotics.github.io
docs_dir: docs/

nav:
  - 中文文档:
      - 首页: zh/index.md
      - SLAM: zh/slam/index.md
      - HTTP Method: zh/slam/http.md
  - English:
      - Home: en/index.md
      - SLAM: en/slam/index.md

theme:
  name: material
  logo: assets/logo_full.svg
  favicon: assets/images/favicon.png
  language: zh
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh